### ISSUE TITLE
Support text profiling result output

### ISSUE THREAD

**Issue by stanzgy** [inconshreveable/sqltap#18]
Thanks for your great tools first. But many times we are using sqlalchemy on remote servers without web service. It's very inconvenient to use sqltap on these servers. Could you add support for creating profiling result output in raw text format?

**Comment by inconshreveable** [comment]
I don't have the bandwidth to build that right now, but if you want to contribute that, I'd be happy to merge it in.

**Comment by stanzgy** [comment]
Okay, I will give it a try.

**Comment by inconshreveable** [comment]
Merged in #20!
