### ISSUE TITLE
KeyError on HTML report

### ISSUE THREAD

**Issue by floqqi** [inconshreveable/sqltap#27]
Every time I want to generate a HTML report with the new version (0.3.10) a `KeyError(count,)` in template rendering happens. I located the error to be here: https://github.com/inconshreveable/sqltap/blob/master/sqltap/sqltap.py#L371

**Comment by inconshreveable** [comment]
Can you show the full trace of where that KeyError is getting raised from?

**Comment by inconshreveable** [comment]
No followup on this, closing.
