### ISSUE TITLE
Virtual memory leak

### ISSUE THREAD

**Issue by NickSablukov** [inconshreveable/sqltap#41]
Hi

I see unnormal situation.
I use sqltap in flask application (start metrics before request and collect after) for prometheus

```  
    @app.before_request
    def app_before_request():
        if "prometheus" in app.extensions:
            request.sql_profiler = sqltap.start()

    @app.after_request
    def app_after_request(response):
        if "prometheus" in app.extensions:
            app.extensions["prometheus"].ExternalServiceMetric.set_sql_metric(
                metrics=request.sql_profiler.collect(),
                service="{}/{}".format(
                    mdl.db.engine.driver, mdl.db.engine.url.database
                ),
            )

        return response
```

and then look at the metrics of Prometheus. during operation, the application actively consumes memory and drops (host in GAE)

![image](https://user-images.githubusercontent.com/11462253/56794887-dba3ea80-6817-11e9-9eff-ad5068ed42de.png)

If I remove the collection of metrics, it will be (11:10)...

![image](https://user-images.githubusercontent.com/11462253/56794935-fb3b1300-6817-11e9-9e7d-1fc286039b80.png)

No one came across this?

**Comment by meoril** [comment]
@NickSablukov i'm not sure if that's the issue, but i think i've had a similar problem during my test runs. it looks like you're adding the before_execute and after_execute event listeners for every request, and never remove them.
