### ISSUE TITLE
SQLAlchemy 1.4 changes the signature of ConnectionEvents before_execute & after_execute

### ISSUE THREAD

**Issue by rsyring** [inconshreveable/sqltap#46]
After upgrading to SQLAlchemy 1.4.22 (from 1.3.x), when using `ProfilingSession`, I now get warnings like:

> SADeprecationWarning: The argument signature for the "ConnectionEvents.before_execute" event listener has changed as of version 1.4, and conversion for the old argument signature will be removed in a future release.  The new signature is "def before_execute(conn, clauseelement, multiparams, params, execution_options)"

And:

> SADeprecationWarning: The argument signature for the "ConnectionEvents.after_execute" event listener has changed as of version 1.4, and conversion for the old argument signature will be removed in a future release.  The new signature is "def after_execute(conn, clauseelement, multiparams, params, execution_options, result)"

**Comment by inconshreveable** [comment]
thanks for raising this issue! happy to take a patch for it if you'd like to contribute one

**Comment by rsyring** [comment]
How do you want to handle backwards compatibility?  Can the next and future releases of sqltap only support SQLAlchemy 1.4+ or do you want to change behavior in sqltap based upon which version of SQLAlchemy is installed?

**Comment by rsyring** [comment]
@inconshreveable any thoughts on how you want to handle backwards compatibility?  See questions above.

**Comment by inconshreveable** [comment]
@rsyring happy to take a suggestion about the correct choice and a pull request with said changes

**Comment by rsyring** [comment]
I put up PR #48 for your review.

**Comment by rsyring** [comment]
@inconshreveable any thoughts on PR #48 above and getting a release out?  I have some client work that is now dependent on this and could do the work to get the PR merged a release out if you'd be interested in taking me or one of my team members on as a maintainer.
